### ISSUE TITLE
Chat.load_models() got an unexpected keyword argument 'local_path'

### ISSUE THREAD

**Issue by whmc76** [shadowcz007/Comfyui-ChatTTS#18]
got prompt
[laugh][uv_break]大家好，我是shadow [uv_break]
result=['[laugh][uv_break]大家好，我是shadow [uv_break]'],len=1
!!! Exception during processing!!! Chat.load_models() got an unexpected keyword argument 'local_path'
Traceback (most recent call last):
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\custom_nodes\Comfyui-ChatTTS\nodes\chat_tts.py", line 190, in chat_tts_run
    result,rand_spk=module.run(audio_file,do_text,self.speaker)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\custom_nodes\Comfyui-ChatTTS\nodes\chat_tts_run.py", line 60, in run
    chat.load_models(local_path=model_local_path,compile=False) # 设置为True以获得更快速度
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chat.load_models() got an unexpected keyword argument 'local_path'

**Comment by whmc76** [comment]
![image](https://github.com/shadowcz007/Comfyui-ChatTTS/assets/129386342/09eb0fc6-b40e-4994-8197-fb85bf39e23d)

**Comment by quqiufeng** [comment]
咋解决的 说一下呢 谢谢

**Comment by whmc76** [comment]
> 咋解决的 说一下呢 谢谢

用了别的TTS哈哈
