### ISSUE TITLE
Error occurred when executing MultiPersonPodcast:  Chat._load() got an unexpected keyword argument 'custom_path'

### ISSUE THREAD

**Issue by quqiufeng** [shadowcz007/Comfyui-ChatTTS#25]
Error occurred when executing MultiPersonPodcast:

Chat._load() got an unexpected keyword argument 'custom_path'

**Comment by quqiufeng** [comment]
got prompt
 使用#speaker 小明 False 
result=['大家好，欢迎收听本周的AI新动态。我是主持人小明，今天我们有两位嘉宾，分别是小李和小王。大家跟听众打个招呼吧！'],len=1
!!! Exception during processing!!! Chat._load() got an unexpected keyword argument 'custom_path'
Traceback (most recent call last):
  File "/root/Comfyui/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/Comfyui/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/Comfyui/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/Comfyui/ComfyUI/custom_nodes/Comfyui-ChatTTS/nodes/chat_tts.py", line 738, in chat_tts_run
    result,rand_spk=module.run(audio_file,do_text,spk,uv_speed,uv_oral,uv_laugh,uv_break,skip_refine_text)
  File "/root/Comfyui/ComfyUI/custom_nodes/Comfyui-ChatTTS/nodes/chat_tts_run.py", line 66, in run
    chat.load_models(source="custom",custom_path=model_local_path,compile=False) # 设置为True以获得更快速度
  File "/root/Comfyui/ComfyUI/custom_nodes/ComfyUI-ChatTTS/ChatTTS/core.py", line 64, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
TypeError: Chat._load() got an unexpected keyword argument 'custom_path'

**Comment by quqiufeng** [comment]
windows 下 也报错
