### ISSUE TITLE
 系统找不到指定的文件

### ISSUE THREAD

**Issue by doubleLife-666** [shadowcz007/Comfyui-ChatTTS#28]
!!! Exception during processing !!! [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "H:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\ComfyUI-aki-v1.3\custom_nodes\Comfyui-ChatTTS\nodes\chat_tts.py", line 941, in ov_run
    module.run(reference_audio['audio_path'],source_audio['audio_path'],save_path,whisper)
  File "H:\ComfyUI-aki-v1.3\custom_nodes\Comfyui-ChatTTS\nodes\openvoice_run.py", line 37, in run
    source_se, audio_name = se_extractor.get_se(src_path, tone_color_converter, target_dir=target_dir,whisper_model=whisper)
  File "H:\ComfyUI-aki-v1.3\custom_nodes\Comfyui-ChatTTS\nodes\openvoice\se_extractor.py", line 154, in get_se
    wavs_folder = split_audio_whisper(audio_path, target_dir=target_dir, audio_name=audio_name,model=whisper_model)
  File "H:\ComfyUI-aki-v1.3\custom_nodes\Comfyui-ChatTTS\nodes\openvoice\se_extractor.py", line 24, in split_audio_whisper
    audio = AudioSegment.from_file(audio_path)
  File "H:\ComfyUI-aki-v1.3\python\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "H:\ComfyUI-aki-v1.3\python\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1720, in runner
  File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 224, in sentry_patched_popen_init
  File "H:\ComfyUI-aki-v1.3\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "H:\ComfyUI-aki-v1.3\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by zyd232** [comment]
用这个
[OpenVoice](https://huggingface.co/myshell-ai/OpenVoice)

别用OpenVoice V2
